### ISSUE TITLE
1.21.1 支持

### ISSUE THREAD

**Issue by hexiruofeng** [RenYuan-MC/Multiverse-Core_Zeta#1]
### Describe the feature

等待更新支持1.21.1

### How is the feature useful to all Multiverse users?

如题

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by lRENyaaa** [comment]
请等待 https://github.com/MikuMC/ZetaUtils 更新

**Comment by Aruvelut-123** [comment]
我看好像已经兼容1.21.1了吧，有一个说兼容1.21.1的issue被关闭了应该是做好了，能否兼容一下 :)

**Comment by lRENyaaa** [comment]
已在 https://github.com/RenYuan-MC/Multiverse-Core_Zeta/commit/29f9c271e393ade036135950b4feda3adf753f7d 和 https://github.com/RenYuan-MC/Multiverse-Core_Zeta/commit/e9c5c8774de7fb225643b0235fc5746ffafb779f 完成1.21.1的支持

**Comment by lRENyaaa** [comment]
可在此下载或自行编译 [multiverse-core-4.3.13-zeta_folia-experimental.zip](https://github.com/user-attachments/files/17274844/multiverse-core-4.3.13-zeta_folia-experimental.zip)
